### ISSUE TITLE
Error launching the ROS node

### ISSUE THREAD

**Issue by jocacace** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#10]
Hi Guys,

I am using Ubuntu 22.04 with the docker image to start ROS2 packages from nvidia. I am trying the tutorial of this example, sadly, ran the isaac_ros_unet node, with the  isaac_ros_unet_triton.launch.py launch file I have the following error:

`[component_container_mt-1] 2022-10-14 13:21:04.108 ERROR gxf/std/entity_executor.cpp@200: Entity with 100 not found!`

Any suggestion?

**Comment by hemalshahNV** [comment]
Running the container on Jammy should be fine. Could you attach more of the log though? The error is probably further up.

**Comment by jocacace** [comment]
This is the whole error:

`[component_container_mt-1] [INFO] [1665755040.173393916] [triton_node]: [NitrosContext] Running appliation...
[component_container_mt-1] [INFO] [1665755040.173529001] [unet_decoder_node]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_unet/share/isaac_ros_unet/SPGKQDAUJG.yaml'
[component_container_mt-1] [INFO] [1665755040.176021770] [unet_decoder_node]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1665755040.176111654] [unet_decoder_node]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1665755040.176189767] [unet_decoder_node]: [NitrosContext] Initializing applicaiton...
[component_container_mt-1] E1014 13:44:00.176364 6926 model_repository_manager.cc:1927] Poll failed for model directory 'peoplesemsegnet_shuffleseg': failed to open text file for read /tmp/models/peoplesemsegnet_shuffleseg/config.pbtxt: No such file or directory
[component_container_mt-1] ERROR: infer_trtis_server.cpp:1051 Triton: failed to load model peoplesemsegnet_shuffleseg, triton_err_str:Internal, err_msg:failed to load 'peoplesemsegnet_shuffleseg', no version is available
[component_container_mt-1] ERROR: infer_trtis_backend.cpp:44 failed to load model: peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: infer_simple_runtime.cpp:32 failed to initialize backend while ensuring model:peoplesemsegnet_shuffleseg ready, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: Error in createNNBackend() <infer_simple_context.cpp:76> [UID = 82]: failed to initialize triton simple runtime for model:peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: Error in initialize() <infer_base_context.cpp:79> [UID = 82]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] 2022-10-14 13:44:00.176 ERROR extensions/triton/inferencers/triton_inferencer_impl.cpp@254: Failure to initialize Inference Context for 'peoplesemsegnet_shuffleseg'
[component_container_mt-1] 2022-10-14 13:44:00.176 ERROR gxf/std/entity_executor.cpp@200: Entity with 100 not found!
[component_container_mt-1] [ERROR] [1665755040.176513401] [triton_node]: [NitrosPublisher] Vault ("vault/vault", eid=100) was stopped. The graph may have been terminated due to an error.
[component_container_mt-1] 2022-10-14 13:44:00.176 WARN  gxf/std/greedy_scheduler.cpp@221: Error while executing entity 82 named 'IBTNLLJWEH_triton_request': GXF_FAILURE
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosPublisher] Vault ("vault/vault", eid=100) was stopped. The graph may have been terminated due to an error.
[ERROR] [component_container_mt-1]: process has died [pid 6926, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container_mt --ros-args -r __node:=unet_container -r __ns:=/'].
`

**Comment by hemalshahNV** [comment]
Thanks, that helps. It looks like it could not find the model file which you'll need to download from NGC and put in place. Take a look at steps 5-7 of the [Quickstart](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#quickstart) if you haven't already.
