### ISSUE TITLE
Failed to get input tensor data!

### ISSUE THREAD

**Issue by yuchenlichuck** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#12]
Hi, there! I change the resolution of input to 512x512, then we I run the model, it shows
`2023-01-04 12:19:42.029 ERROR image_segmentation/segmentation_postprocessor.cpp@78: Failed to get input tensor data!`
What is the reason of it?
Thank you

**Comment by gordongrigor** [comment]
The network requires a specific input format.  

For example if you look at the model card, using [PeopleSemSegNet](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/peoplesemsegnet) states that it requires "_Color Images of resolution 960 X 544 X 3_" as the input.
