### ISSUE TITLE
when I try to install the colcon, it failes with this errors

### ISSUE THREAD

**Issue by yuchenlichuck** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#13]
CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by hemalshahNV** [comment]
Could you post exactly which commands you used to get the above? Catkin is the ROS1 package builder so not sure why it would be showing up here as Isaac ROS packages are for ROS2 (as is colcon).
