### ISSUE TITLE
Image Segmentation in Isaac Gym (the Omniverse version)

### ISSUE THREAD

**Issue by joehays** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#15]
Hello,

Is there any support to be able to use the Image Segmentation capabilities from Isaac ROS Image Segmentation in parallel environments in Omniverse Sim/Gym? The ROS2 layer would have to be stripped away as it's not appropriate for the parallel Gym environments used during the RL training. Is this possible?

**Comment by hemalshahNV** [comment]
Possible, yes, but it would take some work to strip away the ROS 2 layer and integrate the same underlying libraries with Isaac Gym. Alternatively, you can integrate Isaac Gym and Isaac ROS through your own ROS 2 application.

**Comment by joehays** [comment]
ROS is inappropriate when I have over 10k parallel environments running in
Isaac Gym. The power of Isaac Gym is only fully realized when all code runs
on the GPU. Having ROS in the middle removes the primary performance
benefits of Isaac Gym.

**Comment by jaiveersinghNV** [comment]
Isaac ROS Image Segmentation functions using the underlying PeopleSemSegNet model, which is independently available on NGC [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/peoplesemsegnet). The model is distributed as a set of `.etlt` files, which can be decoded into a model engine plan file using `tao-converter` (available [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/resources/tao-converter)) and then loaded by any standard inference engine (Triton, TensorRT, Pytorch, etc.).

You should be able to write your own wrapper function in Python, etc. that loads the model into your inference engine of choice encodes input images, runs inference, and decodes the output images.
