### ISSUE TITLE
 ros2 launch isaac_ros_unet isaac_ros_unet_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1'] network_output_type:='argmax'   error

### ISSUE THREAD

**Issue by kong9999** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#17]
admin@isaac-robot-OMEN:/workspaces/isaac_ros-dev$ ros2 launch isaac_ros_unet isaac_ros_unet_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1'] network_output_type:='argmax'
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-05-06-17-58-58-716934-isaac-robot-OMEN-44146
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container_mt-1]: process started with pid [44157]
[component_container_mt-1] [INFO] [1683367139.122993358] [unet_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_dnn_encoders/lib/libdnn_image_encoder_node.so
[component_container_mt-1] [INFO] [1683367141.883314307] [unet_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode>
[component_container_mt-1] [INFO] [1683367141.883431543] [unet_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode>
[component_container_mt-1] [INFO] [1683367141.892318156] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container_mt-1] [INFO] [1683367141.892565623] [dnn_image_encoder]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1683367141.893421751] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container_mt-1] [INFO] [1683367142.313592290] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container_mt-1] [INFO] [1683367142.789333199] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container_mt-1] [INFO] [1683367143.173993198] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container_mt-1] [INFO] [1683367143.656327313] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container_mt-1] [INFO] [1683367143.660435253] [NitrosContext]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1683367143.664778063] [NitrosContext]: [NitrosContext] Running application...
[component_container_mt-1] 2023-05-06 17:59:03.664 WARN  gxf/std/program.cpp@456: No system specified. Nothing to do
[component_container_mt-1] [INFO] [1683367143.665931722] [dnn_image_encoder]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1683367143.665975427] [dnn_image_encoder]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1683367143.696298122] [dnn_image_encoder]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1683367143.696394782] [dnn_image_encoder]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1683367143.701298720] [dnn_image_encoder]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1683367143.701340995] [dnn_image_encoder]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1683367143.702070540] [dnn_image_encoder]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1683367143.702589842] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container_mt-1] [INFO] [1683367143.745394223] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container_mt-1] [INFO] [1683367143.805760229] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/image_proc/libgxf_tensorops.so
[component_container_mt-1] [INFO] [1683367143.894031855] [dnn_image_encoder]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container_mt-1] [INFO] [1683367143.941471549] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/multimedia/libgxf_multimedia.so
[component_container_mt-1] [INFO] [1683367143.942177109] [dnn_image_encoder]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1683367143.954081872] [dnn_image_encoder]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1683367144.032706321] [dnn_image_encoder]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1683367144.034240552] [dnn_image_encoder]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1683367144.038699359] [dnn_image_encoder]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/dnn_image_encoder' in container '/unet_container'
[component_container_mt-1] [INFO] [1683367144.039879358] [unet_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_triton/lib/libtriton_node.so
[component_container_mt-1] [INFO] [1683367144.040650835] [unet_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container_mt-1] [INFO] [1683367144.040657771] [unet_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container_mt-1] [INFO] [1683367144.041861781] [triton_node]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1683367144.042071273] [triton_node]: [TritonNode] Set input data format to: "nitros_tensor_list_nchw_rgb_f32"
[component_container_mt-1] [INFO] [1683367144.042077182] [triton_node]: [TritonNode] Set output data format to: "nitros_tensor_list_nhwc_rgb_f32"
[component_container_mt-1] [INFO] [1683367144.042106720] [triton_node]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1683367144.042109553] [triton_node]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1683367144.043047661] [triton_node]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1683367144.043054605] [triton_node]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1683367144.043870081] [triton_node]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1683367144.043876246] [triton_node]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1683367144.043968901] [triton_node]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1683367144.044143531] [triton_node]: [NitrosContext] Loading extension: gxf/triton/libgxf_triton_ext.so
[component_container_mt-1] [INFO] [1683367144.163754591] [triton_node]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1683367144.167206906] [triton_node]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1683367144.225266183] [triton_node]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1683367144.229952854] [triton_node]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1683367144.230083723] [triton_node]: [NitrosPublisherSubscriberGroup] Pinning the component "triton_request/input" (type="nvidia::gxf::DoubleBufferReceiver") to use its compatible format only: "nitros_tensor_list_nchw_rgb_f32"
[component_container_mt-1] [INFO] [1683367144.231385138] [triton_node]: [NitrosPublisherSubscriberGroup] Pinning the component "vault/vault" (type="nvidia::gxf::Vault") to use its compatible format only: "nitros_tensor_list_nhwc_rgb_f32"
[component_container_mt-1] [INFO] [1683367144.231664422] [triton_node]: [NitrosNode] Starting negotiation...
[component_container_mt-1] [INFO] [1683367144.231787404] [dnn_image_encoder]: Negotiating
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/triton_node' in container '/unet_container'
[component_container_mt-1] [INFO] [1683367144.232630991] [unet_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_unet/lib/libunet_decoder_node.so
[component_container_mt-1] [INFO] [1683367144.233894639] [unet_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::unet::UNetDecoderNode>
[component_container_mt-1] [INFO] [1683367144.233903015] [unet_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::unet::UNetDecoderNode>
[component_container_mt-1] [INFO] [1683367144.235148118] [unet_decoder_node]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1683367144.235375115] [unet_decoder_node]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1683367144.235381106] [unet_decoder_node]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1683367144.236302741] [unet_decoder_node]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1683367144.236310738] [unet_decoder_node]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1683367144.236686807] [unet_decoder_node]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1683367144.236690999] [unet_decoder_node]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1683367144.236693589] [unet_decoder_node]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1683367144.236836837] [unet_decoder_node]: [NitrosContext] Loading extension: gxf/libgxf_segmentation_postprocessor.so
[component_container_mt-1] [INFO] [1683367144.237258895] [unet_decoder_node]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1683367144.238400895] [unet_decoder_node]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1683367144.262384827] [unet_decoder_node]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1683367144.263732693] [unet_decoder_node]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1683367144.263774712] [unet_decoder_node]: [NitrosPublisherSubscriberGroup] Pinning the component "colored_segmentation_mask_vault/vault" (type="nvidia::gxf::Vault") to use its compatible format only: "nitros_image_rgb8"
[component_container_mt-1] [INFO] [1683367144.264882341] [unet_decoder_node]: [NitrosNode] Starting negotiation...
[component_container_mt-1] [INFO] [1683367144.265064482] [triton_node]: Negotiating
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/unet_decoder_node' in container '/unet_container'
[component_container_mt-1] [INFO] [1683367145.039043237] [dnn_image_encoder]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1683367145.039169073] [dnn_image_encoder]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1683367145.039198538] [dnn_image_encoder]: [NitrosPublisher] Use the negotiated data format: "nitros_tensor_list_nchw_rgb_f32"
[component_container_mt-1] [INFO] [1683367145.039219720] [dnn_image_encoder]: [NitrosSubscriber] Negotiation ended with no results
[component_container_mt-1] [INFO] [1683367145.039234824] [dnn_image_encoder]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/image", data_format="nitros_image_bgr8"
[component_container_mt-1] [INFO] [1683367145.039358487] [dnn_image_encoder]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1683367145.050069360] [dnn_image_encoder]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_dnn_encoders/share/isaac_ros_dnn_encoders/LWXJRVGXBZ.yaml"
[component_container_mt-1] [INFO] [1683367145.050112287] [dnn_image_encoder]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1683367145.050117433] [dnn_image_encoder]: In DNN Image Encoder Node preLoadGraphCallback().
[component_container_mt-1] [INFO] [1683367145.050133791] [dnn_image_encoder]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1683367145.050138222] [dnn_image_encoder]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_dnn_encoders/share/isaac_ros_dnn_encoders/LWXJRVGXBZ.yaml'
[component_container_mt-1] [INFO] [1683367145.052829092] [dnn_image_encoder]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1683367145.052891816] [dnn_image_encoder]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1683367145.052897359] [dnn_image_encoder]: In DNN Image Encoder Node postLoadGraphCallback().
[component_container_mt-1] [INFO] [1683367145.052953604] [dnn_image_encoder]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1683367145.122801285] [dnn_image_encoder]: [NitrosContext] Running application...
[component_container_mt-1] [INFO] [1683367145.231826846] [triton_node]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1683367145.231858080] [triton_node]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1683367145.231862953] [triton_node]: [NitrosSubscriber] Use the negotiated data format: "nitros_tensor_list_nchw_rgb_f32"
[component_container_mt-1] [INFO] [1683367145.231873080] [triton_node]: [NitrosPublisher] Use the negotiated data format: "nitros_tensor_list_nhwc_rgb_f32"
[component_container_mt-1] [INFO] [1683367145.231878029] [triton_node]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1683367145.239768914] [triton_node]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/JXNPYNGECH.yaml"
[component_container_mt-1] [INFO] [1683367145.239785171] [triton_node]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1683367145.239789364] [triton_node]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1683367145.239793679] [triton_node]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/JXNPYNGECH.yaml'
[component_container_mt-1] 2023-05-06 17:59:05.240 WARN  gxf/std/yaml_file_loader.cpp@952: Using unregistered parameter 'dummy_rx' in component 'requester'.
[component_container_mt-1] [INFO] [1683367145.240722032] [triton_node]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1683367145.240751460] [triton_node]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1683367145.240755723] [triton_node]: In TritonNode postLoadGraphCallback().
[component_container_mt-1] [INFO] [1683367145.240818899] [triton_node]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1683367145.265047898] [unet_decoder_node]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1683367145.265098162] [unet_decoder_node]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1683367145.265108201] [unet_decoder_node]: [NitrosPublisher] Negotiation ended with no results
[component_container_mt-1] [INFO] [1683367145.265117192] [unet_decoder_node]: [NitrosPublisher] Use only the compatible publisher: topic_name="/unet/raw_segmentation_mask", data_format="nitros_image_mono8"
[component_container_mt-1] [INFO] [1683367145.265126073] [unet_decoder_node]: [NitrosPublisher] Negotiation ended with no results
[component_container_mt-1] [INFO] [1683367145.265132657] [unet_decoder_node]: [NitrosPublisher] Use only the compatible publisher: topic_name="/unet/colored_segmentation_mask", data_format="nitros_image_rgb8"
[component_container_mt-1] [INFO] [1683367145.265141932] [unet_decoder_node]: [NitrosSubscriber] Use the negotiated data format: "nitros_tensor_list_nhwc_rgb_f32"
[component_container_mt-1] [INFO] [1683367145.265165690] [unet_decoder_node]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] WARNING: infer_trtis_server.cpp:1219 NvDsTritonServerInit suggest to set model_control_mode:none. otherwise may cause unknow issues.
[component_container_mt-1] I0506 09:59:05.292163 44157 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f5c00000000' with size 268435456
[component_container_mt-1] I0506 09:59:05.292285 44157 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
[component_container_mt-1] [INFO] [1683367145.292780257] [unet_decoder_node]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_unet/share/isaac_ros_unet/QCUIGEOMRJ.yaml"
[component_container_mt-1] [INFO] [1683367145.292820539] [unet_decoder_node]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1683367145.292824343] [unet_decoder_node]: [NitrosNode] Loading application
[component_container_mt-1] I0506 09:59:05.292888 44157 server.cc:563]
[component_container_mt-1] +------------------+------+
[component_container_mt-1] | Repository Agent | Path |
[component_container_mt-1] +------------------+------+
[component_container_mt-1] +------------------+------+
[component_container_mt-1]
[component_container_mt-1] I0506 09:59:05.292896 44157 server.cc:590]
[component_container_mt-1] +---------+------+--------+
[component_container_mt-1] | Backend | Path | Config |
[component_container_mt-1] +---------+------+--------+
[component_container_mt-1] +---------+------+--------+
[component_container_mt-1]
[component_container_mt-1] I0506 09:59:05.292901 44157 server.cc:633]
[component_container_mt-1] +-------+---------+--------+
[component_container_mt-1] | Model | Version | Status |
[component_container_mt-1] +-------+---------+--------+
[component_container_mt-1] +-------+---------+--------+
[component_container_mt-1]
[component_container_mt-1] I0506 09:59:05.369985 44157 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3080
[component_container_mt-1] I0506 09:59:05.370114 44157 metrics.cc:757] Collecting CPU metrics
[component_container_mt-1] I0506 09:59:05.370186 44157 tritonserver.cc:2264]
[component_container_mt-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container_mt-1] | Option                           | Value                                                                                                                                                                                                |
[component_container_mt-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container_mt-1] | server_id                        | triton                                                                                                                                                                                               |
[component_container_mt-1] | server_version                   | 2.26.0                                                                                                                                                                                               |
[component_container_mt-1] | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
[component_container_mt-1] | model_repository_path[0]         | /tmp/models                                                                                                                                                                                          |
[component_container_mt-1] | model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                        |
[component_container_mt-1] | strict_model_config              | 1                                                                                                                                                                                                    |
[component_container_mt-1] | rate_limit                       | OFF                                                                                                                                                                                                  |
[component_container_mt-1] | pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
[component_container_mt-1] | cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
[component_container_mt-1] | response_cache_byte_size         | 0                                                                                                                                                                                                    |
[component_container_mt-1] | min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
[component_container_mt-1] | strict_readiness                 | 1                                                                                                                                                                                                    |
[component_container_mt-1] | exit_timeout                     | 30                                                                                                                                                                                                   |
[component_container_mt-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container_mt-1]
[component_container_mt-1] [INFO] [1683367145.370505773] [triton_node]: [NitrosContext] Running application...
[component_container_mt-1] [INFO] [1683367145.370579833] [unet_decoder_node]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_unet/share/isaac_ros_unet/QCUIGEOMRJ.yaml'
[component_container_mt-1] I0506 09:59:05.371478 44157 model_lifecycle.cc:459] loading: peoplesemsegnet_shuffleseg:1
[component_container_mt-1] [INFO] [1683367145.372550653] [unet_decoder_node]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1683367145.372638746] [unet_decoder_node]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1683367145.372740727] [unet_decoder_node]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1683367145.374147202] [unet_decoder_node]: [NitrosContext] Running application...
[component_container_mt-1] I0506 09:59:05.396475 44157 tensorrt.cc:5442] TRITONBACKEND_Initialize: tensorrt
[component_container_mt-1] I0506 09:59:05.396488 44157 tensorrt.cc:5452] Triton TRITONBACKEND API version: 1.10
[component_container_mt-1] I0506 09:59:05.396492 44157 tensorrt.cc:5458] 'tensorrt' TRITONBACKEND API version: 1.10
[component_container_mt-1] I0506 09:59:05.396493 44157 tensorrt.cc:5486] backend configuration:
[component_container_mt-1] {"cmdline":{"auto-complete-config":"false","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
[component_container_mt-1] I0506 09:59:05.396685 44157 tensorrt.cc:5591] TRITONBACKEND_ModelInitialize: peoplesemsegnet_shuffleseg (version 1)
[component_container_mt-1] I0506 09:59:05.397406 44157 tensorrt.cc:5640] TRITONBACKEND_ModelInstanceInitialize: peoplesemsegnet_shuffleseg (GPU device 0)
[component_container_mt-1] I0506 09:59:05.495704 44157 tensorrt.cc:5678] TRITONBACKEND_ModelInstanceFinalize: delete instance state
[component_container_mt-1] I0506 09:59:05.495723 44157 tensorrt.cc:5617] TRITONBACKEND_ModelFinalize: delete model state
[component_container_mt-1] E0506 09:59:05.495730 44157 model_lifecycle.cc:596] failed to load 'peoplesemsegnet_shuffleseg' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
[component_container_mt-1] ERROR: infer_trtis_server.cpp:1057 Triton: failed to load model peoplesemsegnet_shuffleseg, triton_err_str:Invalid argument, err_msg:load failed for model 'peoplesemsegnet_shuffleseg': version 1 is at UNAVAILABLE state: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.;
[component_container_mt-1]
[component_container_mt-1] ERROR: infer_trtis_backend.cpp:54 failed to load model: peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: infer_simple_runtime.cpp:33 failed to initialize backend while ensuring model:peoplesemsegnet_shuffleseg ready, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: Error in createNNBackend() <infer_simple_context.cpp:76> [UID = 103]: failed to initialize triton simple runtime for model:peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] ERROR: Error in initialize() <infer_base_context.cpp:79> [UID = 103]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container_mt-1] 2023-05-06 17:59:05.495 ERROR /workspaces/isaac_ros-dev/src/isaac_ros_dnn_inference/isaac_ros_triton/gxf/triton/inferencers/triton_inferencer_impl.cpp@326: Failure to initialize Inference Context for 'peoplesemsegnet_shuffleseg'
[component_container_mt-1] 2023-05-06 17:59:05.495 ERROR gxf/std/entity_executor.cpp@541: Entity [JXNPYNGECH_triton_request] must be in kStarted or kIdle or kTickPending or kTicking stage before stopping. Current state is StartPending
[component_container_mt-1] 2023-05-06 17:59:05.495 ERROR gxf/std/entity_executor.cpp@203: Entity with eid 121 not found!
[component_container_mt-1] [ERROR] [1683367145.495833517] [triton_node]: [NitrosPublisher] Vault ("vault/vault", eid=121) was stopped. The graph may have been terminated due to an error.
[component_container_mt-1] 2023-05-06 17:59:05.495 WARN  gxf/std/greedy_scheduler.cpp@235: Error while executing entity 103 named 'JXNPYNGECH_triton_request': GXF_FAILURE
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosPublisher] Vault ("vault/vault", eid=121) was stopped. The graph may have been terminated due to an error.
[ERROR] [component_container_mt-1]: process has died [pid 44157, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container_mt --ros-args -r __node:=unet_container -r __ns:=/'].

![Image_20230506180809](https://user-images.githubusercontent.com/51771035/236617835-0f3ca112-54d7-4dae-9e3f-aeb2c6211443.png)

**The model transformation process is as follows**
admin@isaac-robot-OMEN:/tmp/models/peoplesemsegnet_shuffleseg$ /opt/nvidia/tao/tao-converter -k tlt_encode -d 3,544,960 -p input_2:0,1x3x544x960,1x3x544x960,1x3x544x960 -t int8 -c peoplesemsegnet_shuffleseg_cache.txt -e /tmp/models/peoplesemsegnet_shuffleseg/1/model.plan -o argmax_1 peoplesemsegnet_shuffleseg_etlt.etlt
[INFO] [MemUsageChange] Init CUDA: CPU +323, GPU +0, now: CPU 335, GPU 850 (MiB)
[INFO] [MemUsageChange] Init builder kernel library: CPU +416, GPU +116, now: CPU 803, GPU 966 (MiB)
[WARNING] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[INFO] ----------------------------------------------------------------
[INFO] Input filename:   /tmp/filergJUTG
[INFO] ONNX IR version:  0.0.6
[INFO] Opset version:    11
[INFO] Producer name:    tf2onnx
[INFO] Producer version: 1.9.2
[INFO] Domain:
[INFO] Model version:    0
[INFO] Doc string:
[INFO] ----------------------------------------------------------------
[WARNING] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[WARNING] Tensor DataType is determined at build time for tensors not marked as input or output.
[INFO] Detected input dimensions from the model: (-1, 3, 544, 960)
[INFO] Model has dynamic shape. Setting up optimization profiles.
[INFO] Using optimization profile min shape: (1, 3, 544, 960) for input: input_2:0
[INFO] Using optimization profile opt shape: (1, 3, 544, 960) for input: input_2:0
[INFO] Using optimization profile max shape: (1, 3, 544, 960) for input: input_2:0
[INFO] Reading Calibration Cache for calibrator: EntropyCalibration2
[INFO] Generated calibration scales using calibration cache. Make sure that calibration cache has latest scales.
[INFO] To regenerate calibration cache, please delete the existing one. TensorRT will generate a new calibration cache.
[WARNING] Missing scale and zero-point for tensor channel_shuffle_1/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_2/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_3/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_4/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_5/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_6/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_7/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_8/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_9/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_10/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_11/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_12/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_13/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_14/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_15/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor channel_shuffle_16/Reshape_1:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +852, GPU +360, now: CPU 1665, GPU 1326 (MiB)
[INFO] [MemUsageChange] Init cuDNN: CPU +125, GPU +58, now: CPU 1790, GPU 1384 (MiB)
[INFO] Local timing cache in use. Profiling results in this builder pass will not be stored.
[INFO] Some tactics do not have sufficient workspace memory to run. Increasing workspace size will enable more tactics, please check verbose output for requested sizes.
[INFO] Detected 1 inputs and 1 output network tensors.
[INFO] Total Host Persistent Memory: 116144
[INFO] Total Device Persistent Memory: 991232
[INFO] Total Scratch Memory: 16711680
[INFO] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 4 MiB, GPU 698 MiB
[INFO] [BlockAssignment] Algorithm ShiftNTopDown took 2.17698ms to assign 5 blocks to 74 nodes requiring 21428736 bytes.
[INFO] Total Activation Memory: 21428736
[WARNING] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[WARNING] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[WARNING] Check verbose logs for the list of affected weights.
[WARNING] - 45 weights are affected by this issue: Detected subnormal FP16 values.
[WARNING] - 2 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
[INFO] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +1, GPU +4, now: CPU 1, GPU 4 (MiB)
![Image_20230506181753](https://user-images.githubusercontent.com/51771035/236618285-850c1a39-6d81-4e97-af93-02b2a9a47e08.png)

**Comment by jaiveersinghNV** [comment]
We tried to replicate the error on our machines, but we found that the quickstart succeeded on our machines. We've forwarded this to our QA team to see if they're able to reproduce it.

**Comment by jaiveersinghNV** [comment]
Could you provide any other information about your setup? Did you make any changes to the launch file or other configuration?
