### ISSUE TITLE
Unable to locate package ros-humble-isaac-ros-unet

### ISSUE THREAD

**Issue by magic-Alex** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#24]
I tried to run the demo but I can't find package 'ros-humble-isaac-ros-unet' when installing at step 5 of the [Quickstart](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#quickstart), do you have any suggestions

**Comment by magic-Alex** [comment]
with docker

**Comment by kajananchinniahNV** [comment]
Hi,

Could you confirm that everything that you're running is on the latest version? Could you also provide further details about what platform you're running on?

**Comment by magic-Alex** [comment]
> Hi,
> 
> Could you confirm that everything that you're running is on the latest version? Could you also provide further details about what platform you're running on?
> 
> Could you please run this command _inside the container_ and let us know what the output is:
> 
> ```
> sudo apt policy ros-humble-isaac-ros-unet
> ```
> 
> The expected output is something like this:
> 
> ```
>   Installed: (none)
>   Candidate: 2.1.0-0focal
>   Version table:
>      2.1.0-0focal 500
>         500 https://isaac.download.nvidia.com/isaac-ros/ubuntu/main focal/main amd64 Packages
> ```

Thinks,I found out that the package and doc had been updated a few days ago, but my package was previously cloned.I solved the problem by deleting docker images and running the new 'run_dev.sh'.
Then I have a new question, do I need to build a new image every update.

**Comment by magic-Alex** [comment]
> You should only need to exit the container and run 'run_dev.sh' again which will download any new Docker image needed and launch a fresh container against it.
I get it,thinks.

**Comment by magic-Alex** [comment]
Sorry for reopening this issue，I used a new computer and everything worked according to quickStart, but this problem reappeared. I dont understand.
![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation/assets/64207271/10ecba1f-cc17-4644-8f9c-9dc29f644056)

**Comment by magic-Alex** [comment]
> > Sorry for reopening this issue，I used a new computer and everything worked according to quickStart, but this problem reappeared. I dont understand. ![image](https://private-user-images.githubusercontent.com/64207271/288620062-10ecba1f-cc17-4644-8f9c-9dc29f644056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDI3NDksIm5iZiI6MTcwMjAwMjQ0OSwicGF0aCI6Ii82NDIwNzI3MS8yODg2MjAwNjItMTBlY2JhMWYtY2MxNy00NjQ0LThmOWMtOWRjMjlmNjQ0MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OWU0M2E3NWE5NWU1MTg0OGQ2ZjcyYWRmNDJhNWE0Y2UxMGM5NGRjMjg2M2Q1MzNkMjFlMWMyYjEyNjk1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tUtHXHn3ybRvMcAiVeEVQpDMuPhcQl14u3sfVTjCdaQ)
> 
> Have you executed `sudo apt update` before?

No,I think it's not necessary,maybe. Because I tried to run run_dev.sh today,everything worked normally.  So weird,To ensure success each time, what should I pay attention to?

**Comment by hemalshahNV** [comment]
This is very strange indeed. Let us check whether that package itself is being appeared/disappeared from the manifest on the debian repository somehow. That seems suspect.
