### ISSUE TITLE
ISAAC ROS GEMS on JetPack 5.0 without containers

### ISSUE THREAD

**Issue by gsingh-1981** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#4]
Hi, 

i am planning to use isaac_ros_image_segmentation package on AGX Xavier using Jetpack 5.0 by installing ROS2 foxy natively. can you please let me know if this is possible or tested ? if yes, can you please share some steps to follow 
Also, what is roadmap to support isaac ros gems packages  without containers using Jetpack 5.0 on ROS2 foxy/Humble) ? 

Thanks
Gurpreet

**Comment by gsingh-1981** [comment]
Hi, please provide feedbacks

**Comment by hemalshahNV** [comment]
Apologies, my email reply did not get posted.

isaac_ros_image_segmentation is not expected to work on Jetpack 5 DP with ROS2 Foxy and won't be officially supported (read: tested) until our next release expected in June 2022 which will be on ROS2 Humble with optimizations from our collaboration with Open Robotics.

We test with containers but you should be able to setup your native environment the same way using the commands in the Dockerfile (for Jetson only, x86 is a slightly different story).
________________________________

**Comment by gordongrigor** [comment]
Isaac ROS have been updated for Jetpack 5.0.1 developer preview, and tested as working with image segmentation.

**Comment by hemalshahNV** [comment]
isaac_ros_image_segmentation is not expected to work on Jetpack 5 DP with ROS2 Foxy and won't be officially supported (read: tested) until our next release expected in June 2022 which will be on ROS2 Humble with optimizations from our collaboration with Open Robotics.

We test with containers but you should be able to setup your native environment the same way using the commands in the Dockerfile (for Jetson only, x86 is a slightly different story).
________________________________
From: gsingh-1981 ***@***.***>
Sent: Tuesday, May 3, 2022 3:32 AM
To: NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation] ISAAC ROS GEMS on JetPack 5.0 without containers (Issue #4)


Hi,

i am planning to use isaac_ros_image_segmentation package on AGX Xavier using Jetpack 5.0 by installing ROS2 foxy natively. can you please let me know if this is possible or tested ? if yes, can you please share some steps to follow
Also, what is roadmap to support isaac ros gems packages without containers using Jetpack 5.0 on ROS2 foxy/Humble) ?

Thanks
Gurpreet
