### ISSUE TITLE
rqt_image_view is missing

### ISSUE THREAD

**Issue by molnarszilard** [NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation#5]
Hi!

I am trying to run this demo on my Jetson NX. It seems that I can publish a static image, then the triton node processes it, but when I am trying to see the result by running 'ros2 run rqt_image_view rqt_image_view', I get the error:

Package 'rqt_image_view' not found

The same for rviz.

Any help, should I modify something in the dockerfile?

(I have a fresh Jetpack 4.6.1 install on an nvme ssd, deepstream 6.0).

**Comment by hemalshahNV** [comment]
rviz and rQt are not in the Jetson Docker containers unfortunately. Building them from source for Ubuntu 18.04 Bionic has been problematic.  You'll want to run these tools on an x86 machine connected to the same network to visualize.
